import { useEffect, useState } from 'react';

type Quarter = { trimestre: number; cantidadProgramada: number; cantidadEjecutada?: number; observaciones?: string | null; medioVerificacion?: string | null; evidenciaUrl?: string | null };

export function MedicionTrimestralModal({ accionId, nombre, unidadMedida, trimestres, onClose, onSaved }: { accionId: number; nombre: string; unidadMedida: string; trimestres: Quarter[]; onClose: () => void; onSaved: () => void }) {
  const [quarter, setQuarter] = useState(1); const [value, setValue] = useState(''); const [medio, setMedio] = useState(''); const [evidencia, setEvidencia] = useState(''); const [observaciones, setObservaciones] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const selected = trimestres.find((item) => item.trimestre === quarter); const programmed = Number(selected?.cantidadProgramada || 0);
  useEffect(() => { setValue(selected?.cantidadEjecutada === undefined ? '' : String(selected.cantidadEjecutada)); setMedio(selected?.medioVerificacion || ''); setEvidencia(selected?.evidenciaUrl || ''); setObservaciones(selected?.observaciones || ''); }, [quarter, selected?.cantidadEjecutada, selected?.medioVerificacion, selected?.evidenciaUrl, selected?.observaciones]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); const executed = Number(value); if (!Number.isFinite(executed) || executed < 0 || executed > programmed) { setMessage('La cantidad debe estar entre 0 y la cantidad programada.'); return; } setSaving(true); const response = await fetch(`/api/acciones/${accionId}/mediciones-trimestrales`, { method: 'PUT', headers: { Authorization: `Bearer ${localStorage.getItem('token') || ''}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ gestion: 2026, trimestre: quarter, cantidadEjecutada: executed, medioVerificacion: medio, evidenciaUrl: evidencia, observaciones }) }); const body = await response.json(); setSaving(false); if (!response.ok) { setMessage(body.error || 'No se pudo guardar la medición'); return; } onSaved(); onClose(); };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={save} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Registro de medición trimestral</p><h2 className="text-xl font-bold">{nombre}</h2><p className="mt-1 text-sm text-slate-500">Unidad: {unidadMedida}</p></div><button type="button" onClick={onClose} className="text-xl text-slate-400">×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Trimestre<select value={quarter} onChange={(event) => setQuarter(Number(event.target.value))} className="mt-1 w-full rounded-lg border p-2.5">{[1, 2, 3, 4].map((item) => <option key={item} value={item}>T{item} · {['ENE-MAR', 'ABR-JUN', 'JUL-SEP', 'OCT-DIC'][item - 1]}</option>)}</select></label><label className="text-sm font-semibold">Cantidad programada<input readOnly value={programmed} className="mt-1 w-full rounded-lg border bg-slate-50 p-2.5" /></label><label className="text-sm font-semibold sm:col-span-2">Cantidad ejecutada<input required type="number" min="0" max={programmed} step="any" value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm font-semibold">Medio de verificación<input value={medio} onChange={(event) => setMedio(event.target.value)} className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm font-semibold">Enlace de evidencia<input type="url" value={evidencia} onChange={(event) => setEvidencia(event.target.value)} placeholder="https://..." className="mt-1 w-full rounded-lg border p-2.5" /></label><label className="text-sm font-semibold sm:col-span-2">Observaciones / justificación<textarea rows={3} value={observaciones} onChange={(event) => setObservaciones(event.target.value)} className="mt-1 w-full rounded-lg border p-2.5" /></label></div>{message && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={saving} className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Guardar medición</button></div></form></div>;
}
