import type { MatrixAction } from './MatrizPlanificacion';

const format = (value: number) => Number(value || 0).toLocaleString('es-BO', { maximumFractionDigits: 2 });
const percent = (value: number) => `${Math.min(100, Math.max(0, value)).toFixed(1)}%`;

export function ResumenDashboardEje({ acciones, gestion }: { acciones: MatrixAction[]; gestion: number }) {
  const planned = acciones.reduce((sum, action) => sum + action.trimestres.reduce((subtotal, quarter) => subtotal + Number(quarter.cantidadProgramada || 0), 0), 0);
  const executed = acciones.reduce((sum, action) => sum + action.trimestres.reduce((subtotal, quarter) => subtotal + Number(quarter.cantidadEjecutada || 0), 0), 0);
  const registered = acciones.reduce((sum, action) => sum + action.trimestres.filter((quarter) => quarter.medicionRegistrada).length, 0);
  const totalPeriods = acciones.length * 4;
  const progress = planned > 0 ? (executed / planned) * 100 : 0;
  const meta2030 = acciones.reduce((sum, action) => sum + Number(action.meta2030 || 0), 0);
  return <section aria-label="Resumen de cumplimiento" className="mb-5"><div className="mb-2 flex flex-wrap items-center gap-2 rounded-lg bg-white px-3 py-2 text-[11px] shadow-sm ring-1 ring-slate-200"><span className="font-semibold uppercase text-slate-500">Gestión:</span><span className="rounded-md bg-blue-600 px-3 py-1 font-bold text-white">{gestion}</span><span className="ml-2 font-semibold uppercase text-slate-500">Periodicidad:</span><span className="rounded-md bg-blue-50 px-3 py-1 font-semibold text-blue-700">Trimestral (T1 - T4)</span><span className="ml-auto text-slate-500">Resumen físico del eje</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Total acciones del eje</p><p className="mt-2 text-3xl font-bold text-slate-900">{acciones.length}</p><p className="mt-1 text-xs text-slate-500">Catálogo planificado</p></article><article className="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Avance ponderado {gestion}</p><span className="rounded-full bg-cyan-100 px-2 py-1 text-[10px] font-bold text-cyan-700">{registered}/{totalPeriods} mediciones</span></div><p className="mt-2 text-3xl font-bold text-slate-900">{percent(progress)}</p><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${Math.min(100, progress)}%` }} /></div><p className="mt-1 text-xs text-slate-500">{format(executed)} ejecutado de {format(planned)} programado</p></article><article className="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Estado de reporte</p><p className="mt-2 text-3xl font-bold text-slate-900">{registered} <span className="text-lg font-normal text-slate-400">/ {totalPeriods}</span></p><p className="mt-1 text-xs"><span className="font-semibold text-emerald-700">{registered} registrados</span><span className="ml-2 text-rose-600">{Math.max(0, totalPeriods - registered)} pendientes</span></p></article><article className="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Meta acumulada 2026–2030</p><p className="mt-2 text-3xl font-bold text-slate-900">{format(meta2030)}</p><p className="mt-1 text-xs text-slate-500">Meta global del eje</p></article></div></section>;
}
