import { useEffect } from 'react';
import { useForm } from 'react-hook-form';

type FormValues = { cuatrimestre: number; valor_resultado: number; medio_verificacion: string; referencia_verificacion: string; observaciones: string; evidencias: FileList };
type Resultado = { id: number; cuatrimestre: number; valor_resultado: number; medio_verificacion: string | null; referencia_verificacion: string | null; observaciones: string | null };

export function ResultadoModal({ accionId, gestion, resultado, onClose, onSaved }: { accionId: number; gestion: number; resultado?: Resultado; onClose: () => void; onSaved: () => void }) {
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<FormValues>({ defaultValues: { cuatrimestre: resultado?.cuatrimestre ?? 1, valor_resultado: resultado?.valor_resultado ?? 0, medio_verificacion: resultado?.medio_verificacion ?? '', referencia_verificacion: resultado?.referencia_verificacion ?? '', observaciones: resultado?.observaciones ?? '' } });
  useEffect(() => { reset({ cuatrimestre: resultado?.cuatrimestre ?? 1, valor_resultado: resultado?.valor_resultado ?? 0, medio_verificacion: resultado?.medio_verificacion ?? '', referencia_verificacion: resultado?.referencia_verificacion ?? '', observaciones: resultado?.observaciones ?? '' }); }, [resultado, reset]);
  const submit = async (values: FormValues) => { const form = new FormData(); form.append('cuatrimestre', String(values.cuatrimestre)); form.append('gestion', String(gestion)); form.append('valor_resultado', String(values.valor_resultado)); form.append('medio_verificacion', values.medio_verificacion || ''); form.append('referencia_verificacion', values.referencia_verificacion || ''); form.append('observaciones', values.observaciones || ''); Array.from(values.evidencias || []).forEach((file) => form.append('evidencias', file)); const token = localStorage.getItem('token'); const url = resultado ? `/api/resultados-cuatrimestrales/${resultado.id}` : `/api/acciones/${accionId}/cuatrimestres`; const response = await fetch(url, { method: resultado ? 'PUT' : 'POST', headers: { Authorization: `Bearer ${token}` }, body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'No se pudo guardar'); onSaved(); onClose(); };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><form onSubmit={handleSubmit(submit)} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">{resultado ? 'Editar resultado' : 'Registrar resultado'}</h2><p className="text-sm text-slate-500">Gestión {gestion}</p></div><button type="button" onClick={onClose} className="text-xl text-slate-400">×</button></div><label className="mt-5 block text-sm font-semibold">Cuatrimestre<select disabled={Boolean(resultado)} className="mt-2 w-full rounded-lg border p-3" {...register('cuatrimestre', { valueAsNumber: true, required: true, min: 1, max: 3 })}><option value={1}>1.º (enero-abril)</option><option value={2}>2.º (mayo-agosto)</option><option value={3}>3.º (septiembre-diciembre)</option></select></label><label className="mt-4 block text-sm font-semibold">Valor resultado<input type="number" min="0" step="any" className="mt-2 w-full rounded-lg border p-3" {...register('valor_resultado', { valueAsNumber: true, required: 'Ingrese un valor', min: { value: 0, message: 'No puede ser negativo' } })} />{errors.valor_resultado && <span className="text-xs text-red-600">{errors.valor_resultado.message}</span>}</label><label className="mt-4 block text-sm font-semibold">Medio de verificación<input className="mt-2 w-full rounded-lg border p-3" placeholder="Ej.: informe técnico, acta, registro fotográfico" {...register('medio_verificacion', { required: 'Describa el medio de verificación' })} />{errors.medio_verificacion && <span className="text-xs text-red-600">{errors.medio_verificacion.message}</span>}</label><label className="mt-4 block text-sm font-semibold">Referencia o enlace <span className="font-normal text-slate-400">(opcional)</span><input type="text" className="mt-2 w-full rounded-lg border p-3" placeholder="URL, código o ruta del documento" {...register('referencia_verificacion')} /></label><label className="mt-4 block text-sm font-semibold">Archivos de respaldo <span className="font-normal text-slate-400">(opcional)</span><input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.xls,.xlsx" className="mt-2 w-full rounded-lg border p-3 text-sm" {...register('evidencias')} /><span className="mt-1 block text-xs font-normal text-slate-500">PDF, imágenes y Excel. Máximo 10 MB por archivo.</span></label><label className="mt-4 block text-sm font-semibold">Observaciones<textarea rows={3} className="mt-2 w-full rounded-lg border p-3" {...register('observaciones')} /></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={isSubmitting} className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">{isSubmitting ? 'Guardando...' : 'Guardar'}</button></div></form></div>;
}
