type DashboardEje = { codigo: string; nombre: string; acciones: number; programado: number; ejecutado: number; avance: number };
type IconName = 'trend' | 'actions' | 'target' | 'check' | 'chart';

function Icon({ name, className = 'h-6 w-6' }: { name: IconName; className?: string }) {
  const paths: Record<IconName, JSX.Element> = {
    trend: <><path d="M4 16l5-5 4 3 7-8" /><path d="M15 6h5v5" /></>,
    actions: <><rect x="4" y="4" width="16" height="16" rx="3" /><path d="M8 9h8M8 13h5M8 17h3" /></>,
    target: <><circle cx="12" cy="12" r="8" /><circle cx="12" cy="12" r="4" /><circle cx="12" cy="12" r="1" /></>,
    check: <><path d="M5 12l4 4L19 6" /><circle cx="12" cy="12" r="9" /></>,
    chart: <><path d="M5 19V9M12 19V5M19 19v-7" /><path d="M3 19h18" /></>
  };
  return <svg aria-hidden="true" className={className} fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" viewBox="0 0 24 24">{paths[name]}</svg>;
}

export function DashboardWidgets({ data }: { data: DashboardEje[] }) {
  const totals = data.reduce((acc, eje) => ({ acciones: acc.acciones + eje.acciones, programado: acc.programado + Number(eje.programado || 0), ejecutado: acc.ejecutado + Number(eje.ejecutado || 0) }), { acciones: 0, programado: 0, ejecutado: 0 });
  const avance = totals.programado ? (totals.ejecutado / totals.programado) * 100 : 0;
  const cards: { label: string; value: string | number; note: string; color: string; icon: IconName }[] = [{ label: 'Avance global', value: `${avance.toFixed(1)}%`, note: 'ejecutado / programado', color: 'emerald', icon: 'trend' }, { label: 'Acciones registradas', value: totals.acciones, note: 'en los 9 ejes', color: 'blue', icon: 'actions' }, { label: 'Meta programada', value: totals.programado.toLocaleString('es-BO'), note: 'plan acumulado', color: 'amber', icon: 'target' }, { label: 'Meta ejecutada', value: totals.ejecutado.toLocaleString('es-BO'), note: 'avance reportado', color: 'violet', icon: 'check' }];
  const colors: Record<string, string> = { emerald: 'bg-emerald-50 text-emerald-700 ring-emerald-100', blue: 'bg-blue-50 text-blue-700 ring-blue-100', amber: 'bg-amber-50 text-amber-700 ring-amber-100', violet: 'bg-violet-50 text-violet-700 ring-violet-100' };
  return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <article key={card.label} className="group rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{card.label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{card.value}</p><p className="mt-1 text-xs text-slate-500">{card.note}</p></div><span className={`grid h-11 w-11 place-items-center rounded-xl ring-1 transition group-hover:scale-110 ${colors[card.color]}`}><Icon name={card.icon} /></span></div></article>)}</section><section className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Icon name="chart" /></span><div><h2 className="font-bold text-slate-900">Avance por eje</h2><p className="text-sm text-slate-500">Porcentaje ejecutado sobre lo programado</p></div></div><span className="text-xs text-slate-400">0–100%</span></div><div className="mt-6 space-y-4">{data.map((eje) => <div key={eje.codigo}><div className="mb-1 flex justify-between text-sm"><span className="font-medium">Eje {eje.codigo} · {eje.nombre}</span><span className="font-bold text-emerald-700">{Number(eje.avance || 0).toFixed(1)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-teal-400 transition-all" style={{ width: `${Math.min(Number(eje.avance || 0), 100)}%` }} /></div></div>)}</div></article><article className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-blue-50 text-blue-700"><Icon name="target" /></span><div><h2 className="font-bold text-slate-900">Programado vs ejecutado</h2><p className="text-sm text-slate-500">Resumen consolidado del plan</p></div></div><div className="mx-auto mt-7 grid h-44 w-44 place-items-center rounded-full" style={{ background: `conic-gradient(#059669 ${Math.min(avance, 100)}%, #e2e8f0 0)` }}><div className="grid h-32 w-32 place-items-center rounded-full bg-white text-center"><strong className="text-2xl">{avance.toFixed(1)}%</strong><span className="text-xs text-slate-500">ejecutado</span></div></div><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Programado</span><strong>{totals.programado.toLocaleString('es-BO')}</strong></div><div className="flex justify-between"><span className="text-slate-500">Ejecutado</span><strong className="text-emerald-700">{totals.ejecutado.toLocaleString('es-BO')}</strong></div></div></article></section></>;
}
