INSERT INTO instituciones (siglas, nombre, ministerio, rol) VALUES
  ('MG', 'Ministerio de Gobierno', NULL, 'apoyo'),
  ('MD', 'Ministerio de Defensa', NULL, 'apoyo'),
  ('MSyD', 'Ministerio de Salud y Deportes', NULL, 'apoyo'),
  ('MPSMAyA', 'Ministerio de Producción Sostenible, Medio Ambiente y Agua', NULL, 'apoyo'),
  ('ME', 'Ministerio de Educación', NULL, 'apoyo'),
  ('MEyFP', 'Ministerio de Economía y Finanzas Públicas', NULL, 'apoyo'),
  ('MDPRyA', 'Ministerio de Desarrollo Productivo Rural y Agua', NULL, 'apoyo'),
  ('DGFELCN', 'Dirección General de la Fuerza Especial de Lucha Contra el Narcotráfico', NULL, 'ejecutor'),
  ('VLICN', 'Viceministerio de Lucha Integral Contra el Narcotráfico', NULL, 'coordinador'),
  ('DGDSyLCN', 'Dirección General de Defensa Social y Lucha Contra el Narcotráfico', NULL, 'coordinador'),
  ('FFAA-CEO', 'Fuerzas Armadas - Comando Estratégico Operacional "Tte. Gironda"', NULL, 'coordinador'),
  ('FTE-DR', 'Fuerza de Tarea Especial "Diablos Rojos"', NULL, 'ejecutor'),
  ('FTE-DN', 'Fuerza de Tarea Especial "Diablos Negros"', NULL, 'ejecutor'),
  ('FTE-DA', 'Fuerza de Tarea Especial "Diablos Azules"', NULL, 'ejecutor'),
  ('FTE-DV', 'Fuerza de Tarea Especial "Diablos Verdes"', NULL, 'ejecutor'),
  ('UIF', 'Unidad de Investigación Financiera', NULL, 'ejecutor'),
  ('DIRCABI', 'Dirección de Registro, Control y Administración de Bienes Incautados', NULL, 'ejecutor'),
  ('AGEMED', 'Agencia Estatal de Medicamentos y Tecnologías en Salud', NULL, 'ejecutor'),
  ('DGSC', 'Dirección General de Sustancias Controladas', NULL, 'ejecutor'),
  ('VDAyA', 'Viceministerio de Desarrollo Agropecuario y Agroforestal', NULL, 'ejecutor'),
  ('OBSCD', 'Observatorio Boliviano de Seguridad Ciudadana y Lucha Contra las Drogas', NULL, 'apoyo'),
  ('DIPREVCON', 'Dirección de Apoyo a la Prevención del Consumo de Drogas, Control del Tráfico Ilícito de Sustancias Controladas y Coca Excedentaria', NULL, 'apoyo'),
  ('GIAEF', 'Grupo de Investigación de Análisis Financiero', NULL, NULL),
  ('VDSSC', 'Viceministerio de Defensa Social y Sustancias Controladas', NULL, NULL)
ON CONFLICT (siglas) DO NOTHING;
