BEGIN;

INSERT INTO ejes (codigo, nombre, objetivo, indicadores_principales, resultados_2030)
VALUES (
  '7',
  'Prevención Integral, Tratamiento, Rehabilitación y Reintegración desde la Salud Pública',
  'Reducir las vulnerabilidades asociadas al consumo de drogas y fortalecer factores de protección en la población boliviana mediante la implementación de un modelo integral de salud pública, basado en evidencia científica, derechos humanos, enfoque de género, enfoque generacional, enfoque diferencial, pertinencia cultural y no discriminación.',
  'Porcentaje de avance en el fortalecimiento y operativización de la Red de Prevención Integral, Tratamiento, Rehabilitación y Reintegración; Porcentaje de avance en el diseño e implementación de la Política de Prevención Integral, Tratamiento, Rehabilitación y Reintegración de personas con adicciones y su entorno; Número de alianzas interinstitucionales promovidas; Número de personas atendidas por consumo problemático de drogas y/o sustancias; Porcentaje de Avance en la implementación de servicios de emergencia para situaciones agudas de consumo, sobredosis o crisis psicóticas de drogas sintética; Porcentaje de Avance en la Implementación del Sistema de Alerta Temprana; Número de estudios de prevalencia y caracterización del consumo de sustancias en población general, escolar, universitaria, con mayor cobertura territorial, y en situación de calle y otros grupos en condición de alta vulnerabilidad.',
  'Red de Prevención Integral, Tratamiento, Rehabilitación y Reintegración operativizada; Política de Prevención Integral, Tratamiento, Rehabilitación y Reintegración de personas con adicciones y su entorno implementada; 31 alianzas interinstitucionales promovidas; 30.000 personas atendidas por consumo problemático de drogas y/o sustancias; Implementación de servicios de emergencia para situaciones agudas de consumo, sobredosis o crisis psicóticas de drogas sintética implementada; Sistema de Alerta Temprana implementada; 7 estudios de prevalencia y caracterización del consumo de sustancias en población general, escolar, universitaria, con mayor cobertura territorial, y en situación de calle y otros grupos en condición de alta vulnerabilidad.'
)
ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, objetivo=EXCLUDED.objetivo, indicadores_principales=EXCLUDED.indicadores_principales, resultados_2030=EXCLUDED.resultados_2030;

WITH eje AS (SELECT id FROM ejes WHERE codigo='7'),
fuente (codigo,nombre,resultado,indicador_proceso,unidad_medida,meta_2030,siglas_responsable,instituciones_apoyo,orden) AS (
VALUES
('7.1','Operativizar la Red de Prevención Integral, Tratamiento, Rehabilitación y Reintegración, creada por la Ley N.º 913, a fin de implementar un Sistema Nacional de Prevención Integral y Atención de Drogas interoperable, con participación de instituciones públicas, privadas y gobiernos subnacionales.','Red de Prevención Integral, Tratamiento, Rehabilitación y Reintegración, creada por la Ley N.º 913 operativizada','Porcentaje de avance en la operativización de la Red de Prevención Integral, Tratamiento, Rehabilitación y Reintegración.','%',100,'MG','MSyD;ME',1),
('7.2','Diseñar e implementar la Política de Prevención Integral, Tratamiento, Rehabilitación y Reintegración de personas con adicciones y su entorno.','Política de Prevención Integral, Tratamiento, Rehabilitación y Reintegración de personas con adicciones y su entorno diseñada e implementada','Porcentaje de avance en el diseño e implementación de la Política de Prevención Integral, Tratamiento, Rehabilitación y Reintegración de personas con adicciones y su entorno.','%',100,'MG','MSyD;ME',2),
('7.3','Promover alianzas interinstitucionales con entidades públicas, privadas, académicas y organizaciones de la sociedad civil vinculadas a prevención, tratamiento, rehabilitación, reintegración e investigación científica','Alianzas interinstitucionales con entidades públicas, privadas, académicas y organizaciones de la sociedad civil vinculadas a prevención, tratamiento, rehabilitación, reintegración e investigación científica promovidas','Número de alianzas interinstitucionales promovidas','número',31,'VLICN','MG',3),
('7.4','Fortalecer la coordinación territorial entre nivel central, departamental y municipal a través de la asistencia técnica para la formulación de Planes Municipales de prevención.','Coordinación territorial entre nivel central, departamental y municipal fortalecida','Número de mesas técnicas conformadas','número',177,'MG','MSyD',4),
('7.5','Implementar programas de prevención universal basados en evidencia en el sistema educativo.','Programas de prevención universal basados en evidencia en el sistema educativo implementadas','Porcentaje de avance en la implementación de programas de prevención universal','%',100,'MG','ME;MSyD',5),
('7.6','Implementar programas de fortalecimiento familiar basados en estándares internacionales de prevención universal, selectiva e indicada.','Programas de fortalecimiento familiar basados en estándares internacionales de prevención universal, selectiva e indicada implementadas','Porcentaje de Avance en la implementación de programas de fortalecimiento familiar','%',100,'MG','ME;MSyD',6),
('7.7','Implementar programas de prevención selectiva e indicada en grupos de mayor riesgo, como jóvenes expuestos a violencia, abandono escolar, consumo temprano o vulnerabilidad psicosocial.','Programas de prevención selectiva e indicada en grupos de mayor riesgo, como jóvenes expuestos a violencia, abandono escolar, consumo temprano o vulnerabilidad psicosocial implementadas','Porcentaje de Avance en la implementación de programas de prevención selectiva e indicada','%',100,'MG','ME;MSyD',7),
('7.8','Implementar lineamientos técnicos y operativos de detección temprana e intervención breve en entornos educativos, de salud y comunitarios.','Lineamientos técnicos y operativos de detección temprana e intervención breve en entornos educativos, de salud y comunitarios implementadas','Porcentaje de implementación de Lineamientos técnicos operativos en el primer nivel de atención','%',100,'MSyD',NULL,8),
('7.9','Diseñar, implementar y regular campañas de comunicación complementadas por materiales educativos, procesos formativos, programas escolares y familiares basados en evidencia, orientadas a reforzar factores de protección, romper estigmas y fomentar ayuda temprana.','Campañas de comunicación diseñadas implementadas y reguladas','Porcentaje de avance en el diseño, implementación y regulación de las campañas de comunicación.','%',100,'MG','ME;MSyD;DGFELCN',9),
('7.10','Implementar lineamientos de prevención del consumo de sustancias en entornos laborales.','Lineamientos de prevención del consumo de sustancias en entornos laborales implementadas','Porcentaje de avance en la implementación de lineamientos de prevención del consumo de sustancias en entornos laborales','%',100,'MG',NULL,10),
('7.11','Fortalecer el intercambio de buenas prácticas, asistencia técnica, evidencia científica y experiencias internacionales en materia de prevención integral, tratamiento, rehabilitación y reintegración, en coordinación con los organismos internacionales','Intercambio de buenas prácticas, asistencia técnica, evidencia científica y experiencias internacionales en materia de prevención integral, tratamiento, rehabilitación y reintegración, en coordinación con los organismos internacionales fortalecidas','Número intercambio de buenas prácticas, asistencia técnica, evidencia científica y experiencias internacionales','número',46,'MG','ME;MSyD;DGFELCN',11),
('7.13','Establecer un Mecanismo Nacional de Acreditación y Supervisión para centros públicos y privados que realizan atención y abordaje integral de adicciones, de conformidad con los estándares internacionales.','Mecanismo Nacional de Acreditación y Supervisión para centros públicos y privados, conforme a estándares internacionales establecidos','Porcentaje de Avance en el establecimiento de un Mecanismo Nacional de Acreditación y Supervisión','%',100,'MSyD',NULL,13),
('7.14','Garantizar la atención integral de personas con consumo problemático de sustancias, sustentada en evidencia científica e integrada al modelo de salud mental comunitaria.','Atención de personas con consumo problemático de drogas basada en evidencia científica, incorporando salud mental comunitaria garantizada','Número de personas atendidas por consumo problemático de drogas y/o sustancias','número',30000,'MSyD',NULL,14),
('7.15','Implementar protocolos de atención integral específicos para mujeres, jóvenes, niñas, niños, adolescentes, población en situación de calle y grupos vulnerables.','Protocolos de atención integral específicos para mujeres, jóvenes, niñas, niños, adolescentes, población en situación de calle y grupos vulnerables implementada','Porcentaje de avance en la implementación de protocolos de atención integral','%',100,'MSyD',NULL,15),
('7.16','Implementar programas de prevención indicada para grupos de alto riesgo.','Programas de prevención indicada para grupos de alto riesgo implementadas','Número de programas de prevención indicada para grupos de alto riesgo','número',1,'MG','ME;MSyD',16),
('7.17','Implementar servicios de emergencia para situaciones agudas de consumo, sobredosis o crisis psicóticas por drogas sintéticas.','Servicios de emergencia para situaciones agudas de consumo, sobredosis o crisis psicóticas por drogas sintéticas implementadas','Porcentaje de Avance en la implementación de servicios de emergencia para situaciones agudas de consumo, sobredosis o crisis psicóticas de drogas sintética','%',100,'MSyD',NULL,17),
('7.18','Garantizar la atención de personas con adicciones bajo el Programa de Salud Mental y Adicciones con intervención en Terapia Ocupacional.','Atención de personas con adicciones bajo el Programa de Salud Mental y Adicciones con intervención en Terapia Ocupacional garantizada','Número personas atendidas bajo el Programa de Salud Mental y Adicciones','número',2000,'MSyD',NULL,18),
('7.19','Implementar el Sistema Nacional de Alerta Temprana de Drogas (SINATD) para la detección, validación y emisión oportuna de alertas rápidas sobre Nuevas Sustancias Psicoactivas (NSP), drogas emergentes y variaciones en las tendencias de consumo hacia fármacos de prescripción y fortalecer las capacidades nacionales para la identificación, monitoreo y respuesta temprana frente a las nuevas sustancias psicoactivas y drogas sintéticas emergentes.','Sistema Nacional de Alerta Temprana de Drogas (SINATD) implementada','Porcentaje de Avance en la Implementación del Sistema de Alerta Temprana','%',100,'OBSCD',NULL,19),
('7.20','Actualizar estudios de prevalencia y caracterización del consumo de sustancias en población general, escolar, universitaria, con mayor cobertura territorial, y en situación de calle y otros grupos en condición de alta vulnerabilidad social bajo los estándares metodológicos Internacionales.','Estudios de prevalencia y caracterización del consumo de sustancias actualizada','Número de estudios de prevalencia y caracterización del consumo de sustancias en población general, escolar, universitaria, con mayor cobertura territorial, y en situación de calle y otros grupos en condición de alta vulnerabilidad actualizada','número',7,'OBSCD',NULL,20),
('7.21','Fortalecer la capacidad operativa, técnica y tecnológica del Sistema Nacional de Información sobre Seguridad Estatal (SNISE)','Capacidad operativa, técnica y tecnológica del Sistema Nacional de Información sobre Seguridad Estatal (SNISE) fortalecida','Porcentaje de avance en el fortalecimiento operativo, técnico y tecnológico del SNISE.','%',100,'OBSCD',NULL,21),
('7.22','Implementar en el SNISE, un subsistema de Monitoreo y Evaluación de programas e intervenciones de prevención integral, tratamiento, rehabilitación y reintegración social, con indicadores de proceso, resultado e impacto, orientado a medir la efectividad, sostenibilidad y pertinencia de las acciones implementadas, así como generar evidencia para el fortalecimiento continuo de la política pública.','Subsistema de Monitoreo y Evaluación de programas e intervenciones de prevención integral, tratamiento, rehabilitación y reintegración social, con indicadores de proceso, resultado e impacto, orientado a medir la efectividad, sostenibilidad y pertinencia de las acciones implementadas, así como generar evidencia para el fortalecimiento continuo de la política pública implementada','Porcentaje de avance en el diseño e implementación del subsistema.','%',100,'OBSCD',NULL,22),
('7.23','Promover la coordinación interinstitucional, para la recolección, integración, análisis y monitoreo de información sobre consumo de drogas, factores de riesgo, factores de protección, tendencias emergentes, tratamiento y rehabilitación.','Coordinación interinstitucional, para la recolección, integración, análisis y monitoreo de información sobre consumo de drogas, factores de riesgo, factores de protección, tendencias emergentes, tratamiento y rehabilitación promovida','Número de Convenios o protocolos de intercambio seguro de datos firmados y activos.','número',5,'OBSCD',NULL,23)
), acciones_insertadas AS (
INSERT INTO acciones (eje_id,codigo,nombre,resultado,indicador_proceso,unidad_medida,meta_2030,institucion_principal_id,instituciones_apoyo,orden)
SELECT eje.id,fuente.codigo,fuente.nombre,fuente.resultado,fuente.indicador_proceso,fuente.unidad_medida,fuente.meta_2030,instituciones.id,fuente.instituciones_apoyo,fuente.orden FROM fuente CROSS JOIN eje JOIN instituciones ON instituciones.siglas=fuente.siglas_responsable
ON CONFLICT (eje_id,codigo) DO UPDATE SET nombre=EXCLUDED.nombre,resultado=EXCLUDED.resultado,indicador_proceso=EXCLUDED.indicador_proceso,unidad_medida=EXCLUDED.unidad_medida,meta_2030=EXCLUDED.meta_2030,institucion_principal_id=EXCLUDED.institucion_principal_id,instituciones_apoyo=EXCLUDED.instituciones_apoyo,orden=EXCLUDED.orden RETURNING id,codigo
)
INSERT INTO metas_fisicas (accion_id,gestion,valor_programado)
SELECT acciones_insertadas.id,metas.gestion,metas.valor FROM acciones_insertadas JOIN (VALUES
('7.1',2026,60),('7.1',2027,10),('7.1',2028,10),('7.1',2029,10),('7.1',2030,10),
('7.2',2026,60),('7.2',2027,10),('7.2',2028,10),('7.2',2029,10),('7.2',2030,10),
('7.3',2026,3),('7.3',2027,7),('7.3',2028,7),('7.3',2029,7),('7.3',2030,7),
('7.4',2026,0),('7.4',2027,45),('7.4',2028,45),('7.4',2029,45),('7.4',2030,42),
('7.5',2026,0),('7.5',2027,30),('7.5',2028,30),('7.5',2029,20),('7.5',2030,20),
('7.6',2026,0),('7.6',2027,30),('7.6',2028,30),('7.6',2029,20),('7.6',2030,20),
('7.7',2026,0),('7.7',2027,30),('7.7',2028,30),('7.7',2029,20),('7.7',2030,20),
('7.8',2026,0),('7.8',2027,25),('7.8',2028,25),('7.8',2029,25),('7.8',2030,25),
('7.9',2026,25),('7.9',2027,30),('7.9',2028,25),('7.9',2029,10),('7.9',2030,10),
('7.10',2026,60),('7.10',2027,10),('7.10',2028,10),('7.10',2029,10),('7.10',2030,10),
('7.11',2026,6),('7.11',2027,10),('7.11',2028,10),('7.11',2029,10),('7.11',2030,10),
('7.13',2026,0),('7.13',2027,0),('7.13',2028,40),('7.13',2029,40),('7.13',2030,20),
('7.14',2026,5000),('7.14',2027,5500),('7.14',2028,6000),('7.14',2029,6500),('7.14',2030,7000),
('7.15',2026,0),('7.15',2027,0),('7.15',2028,40),('7.15',2029,40),('7.15',2030,20),
('7.16',2026,0),('7.16',2027,0),('7.16',2028,0),('7.16',2029,1),('7.16',2030,0),
('7.17',2026,0),('7.17',2027,0),('7.17',2028,20),('7.17',2029,30),('7.17',2030,50),
('7.18',2026,0),('7.18',2027,0),('7.18',2028,0),('7.18',2029,800),('7.18',2030,1200),
('7.19',2026,5),('7.19',2027,35),('7.19',2028,40),('7.19',2029,15),('7.19',2030,5),
('7.20',2026,0),('7.20',2027,1),('7.20',2028,2),('7.20',2029,2),('7.20',2030,2),
('7.21',2026,10),('7.21',2027,35),('7.21',2028,35),('7.21',2029,10),('7.21',2030,10),
('7.22',2026,5),('7.22',2027,30),('7.22',2028,50),('7.22',2029,10),('7.22',2030,5),
('7.23',2026,1),('7.23',2027,1),('7.23',2028,1),('7.23',2029,1),('7.23',2030,1)
) AS metas(codigo,gestion,valor) ON metas.codigo=acciones_insertadas.codigo
ON CONFLICT (accion_id,gestion) DO UPDATE SET valor_programado=EXCLUDED.valor_programado;

COMMIT;
