import bcrypt from 'bcrypt';
import type { Request, Response } from 'express';
import type { Pool } from 'pg';

const send = (res: Response, status: number, data: unknown, error: string | null = null) => res.status(status).json({ success: status < 400, data, error });

async function audit(pool: Pool, req: Request, action: 'INSERT' | 'UPDATE' | 'DELETE', id: number, before: unknown, after: unknown) {
  await pool.query('INSERT INTO auditoria(tabla_afectada,registro_id,accion,usuario_id,datos_anteriores,datos_nuevos) VALUES($1,$2,$3,$4,$5,$6)', ['usuarios', id, action, req.user?.id ?? null, before ? JSON.stringify(before) : null, after ? JSON.stringify(after) : null]);
}

export function createAdminController(pool: Pool) {
  const validRole = async (codigo: string) => Boolean((await pool.query('SELECT 1 FROM roles WHERE codigo=$1 AND activo=true', [codigo])).rows[0]);
  return {
    listUsers: async (req: Request, res: Response) => { try { const search = String(req.query.search || ''); const rol = String(req.query.rol || ''); const activo = req.query.activo === undefined ? null : req.query.activo === 'true'; const result = await pool.query(`SELECT u.id,u.username,u.nombre_completo,u.email,u.institucion_id,i.siglas AS institucion,u.rol,u.activo,u.created_at FROM usuarios u LEFT JOIN instituciones i ON i.id=u.institucion_id WHERE ($1='' OR u.username ILIKE '%'||$1||'%' OR COALESCE(u.nombre_completo,'') ILIKE '%'||$1||'%') AND ($2='' OR u.rol=$2) AND ($3::boolean IS NULL OR u.activo=$3) ORDER BY u.id`, [search, rol, activo]); return send(res, 200, result.rows); } catch { return send(res, 500, null, 'No se pudo listar usuarios'); } },
    createUser: async (req: Request, res: Response) => { const { username, password, nombre_completo, email, institucion_id, rol } = req.body || {}; if (!username || !password || !rol || !(await validRole(rol))) return send(res, 400, null, 'Usuario, contraseña y rol válido son requeridos'); try { const hash = await bcrypt.hash(password, 12); const result = await pool.query('INSERT INTO usuarios(username,password_hash,nombre_completo,email,institucion_id,rol) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,username,nombre_completo,email,institucion_id,rol,activo,created_at', [username, hash, nombre_completo || null, email || null, institucion_id || null, rol]); await audit(pool, req, 'INSERT', result.rows[0].id, null, result.rows[0]); return send(res, 201, result.rows[0]); } catch (error: any) { return send(res, error?.code === '23505' ? 409 : 400, null, 'No se pudo crear el usuario'); } },
    updateUser: async (req: Request, res: Response) => { const id = Number(req.params.id); const { username, nombre_completo, email, institucion_id, rol } = req.body || {}; if (!Number.isInteger(id) || !username || !rol || !(await validRole(rol))) return send(res, 400, null, 'Datos inválidos'); try { const old = await pool.query('SELECT id,username,nombre_completo,email,institucion_id,rol,activo FROM usuarios WHERE id=$1', [id]); if (!old.rows[0]) return send(res, 404, null, 'Usuario no encontrado'); const result = await pool.query('UPDATE usuarios SET username=$1,nombre_completo=$2,email=$3,institucion_id=$4,rol=$5 WHERE id=$6 RETURNING id,username,nombre_completo,email,institucion_id,rol,activo,created_at', [username, nombre_completo || null, email || null, institucion_id || null, rol, id]); await audit(pool, req, 'UPDATE', id, old.rows[0], result.rows[0]); return send(res, 200, result.rows[0]); } catch { return send(res, 400, null, 'No se pudo actualizar el usuario'); } },
    changeStatus: async (req: Request, res: Response) => { const id = Number(req.params.id); const activo = Boolean(req.body?.activo); if (!Number.isInteger(id)) return send(res, 400, null, 'Identificador inválido'); if (id === req.user?.id) return send(res, 400, null, 'No puede desactivar su propio usuario'); try { const old = await pool.query('SELECT id,username,rol,activo FROM usuarios WHERE id=$1', [id]); if (!old.rows[0]) return send(res, 404, null, 'Usuario no encontrado'); const result = await pool.query('UPDATE usuarios SET activo=$1 WHERE id=$2 RETURNING id,username,rol,activo', [activo, id]); await audit(pool, req, 'UPDATE', id, old.rows[0], result.rows[0]); return send(res, 200, result.rows[0]); } catch { return send(res, 500, null, 'No se pudo cambiar el estado'); } },
    changePassword: async (req: Request, res: Response) => { const id = Number(req.params.id); if (!Number.isInteger(id) || typeof req.body?.password !== 'string' || req.body.password.length < 8) return send(res, 400, null, 'La contraseña debe tener al menos 8 caracteres'); try { const exists = await pool.query('SELECT id,username FROM usuarios WHERE id=$1', [id]); if (!exists.rows[0]) return send(res, 404, null, 'Usuario no encontrado'); const hash = await bcrypt.hash(req.body.password, 12); await pool.query('UPDATE usuarios SET password_hash=$1 WHERE id=$2', [hash, id]); await audit(pool, req, 'UPDATE', id, { username: exists.rows[0].username, password_changed: false }, { username: exists.rows[0].username, password_changed: true }); return send(res, 200, { id, password_changed: true }); } catch { return send(res, 500, null, 'No se pudo cambiar la contraseña'); } },
    listRoles: async (_req: Request, res: Response) => { try { const result = await pool.query('SELECT r.*, COUNT(u.id)::int AS usuarios_asignados FROM roles r LEFT JOIN usuarios u ON u.rol=r.codigo GROUP BY r.id ORDER BY r.sistema DESC,r.nombre'); return send(res, 200, result.rows); } catch { return send(res, 500, null, 'No se pudo listar roles'); } },
    createRole: async (req: Request, res: Response) => { const { codigo, nombre, descripcion } = req.body || {}; if (!codigo || !nombre || !/^[a-z0-9_]+$/.test(codigo)) return send(res, 400, null, 'Código y nombre válidos son requeridos'); try { const result = await pool.query('INSERT INTO roles(codigo,nombre,descripcion) VALUES($1,$2,$3) RETURNING *', [codigo, nombre, descripcion || null]); await audit(pool, req, 'INSERT', result.rows[0].id, null, result.rows[0]); return send(res, 201, result.rows[0]); } catch { return send(res, 409, null, 'No se pudo crear el rol'); } },
    updateRole: async (req: Request, res: Response) => { const id = Number(req.params.id); const { nombre, descripcion } = req.body || {}; if (!Number.isInteger(id) || !nombre) return send(res, 400, null, 'Datos inválidos'); try { const old = await pool.query('SELECT * FROM roles WHERE id=$1', [id]); if (!old.rows[0]) return send(res, 404, null, 'Rol no encontrado'); const result = await pool.query('UPDATE roles SET nombre=$1,descripcion=$2,updated_at=NOW() WHERE id=$3 RETURNING *', [nombre, descripcion || null, id]); await audit(pool, req, 'UPDATE', id, old.rows[0], result.rows[0]); return send(res, 200, result.rows[0]); } catch { return send(res, 400, null, 'No se pudo actualizar el rol'); } },
    changeRoleStatus: async (req: Request, res: Response) => { const id = Number(req.params.id); const activo = Boolean(req.body?.activo); try { const old = await pool.query('SELECT * FROM roles WHERE id=$1', [id]); if (!old.rows[0]) return send(res, 404, null, 'Rol no encontrado'); if (old.rows[0].sistema) return send(res, 400, null, 'Los roles de sistema no se pueden desactivar'); if (!activo && Number((await pool.query('SELECT COUNT(*) FROM usuarios WHERE rol=$1 AND activo=true', [old.rows[0].codigo])).rows[0].count) > 0) return send(res, 409, null, 'El rol tiene usuarios activos'); const result = await pool.query('UPDATE roles SET activo=$1,updated_at=NOW() WHERE id=$2 RETURNING *', [activo, id]); await audit(pool, req, 'UPDATE', id, old.rows[0], result.rows[0]); return send(res, 200, result.rows[0]); } catch { return send(res, 500, null, 'No se pudo cambiar el estado del rol'); } },
    audit: async (req: Request, res: Response) => { try { const result = await pool.query(`SELECT a.id,a.tabla_afectada,a.registro_id,a.accion,a.usuario_id,u.username,a.datos_anteriores,a.datos_nuevos,a.fecha FROM auditoria a LEFT JOIN usuarios u ON u.id=a.usuario_id WHERE ($1='' OR a.accion=$1) ORDER BY a.fecha DESC LIMIT 200`, [String(req.query.accion || '')]); return send(res, 200, result.rows); } catch { return send(res, 500, null, 'No se pudo consultar la auditoría'); } },
    institutions: async (_req: Request, res: Response) => { try { const result = await pool.query('SELECT id,siglas,nombre FROM instituciones WHERE activo=true ORDER BY siglas'); return send(res, 200, result.rows); } catch { return send(res, 500, null, 'No se pudo listar instituciones'); } }
  };
}
