import { useEffect, useState } from 'react';
import { AccionPlanificacionModal } from './AccionPlanificacionModal';

type Institution = { id: number; siglas: string; nombre: string };
type Action = { accion_id: number; codigo: string; entidad: string | null; entidad_id: number | null; nombre: string; resultado: string | null; tipo_accion: string | null; unidad_medida: string | null; linea_base: number | null; medio_verificacion: string | null; meta_2030: number | null; meta_2026: number; estado_planificacion: string; trimestres: { trimestre: number; cantidadProgramada: number }[] };

export function MatrizPlanificacion({ instituciones }: { instituciones: Institution[] }) {
  const [eje, setEje] = useState('1'); const [acciones, setAcciones] = useState<Action[]>([]); const [editing, setEditing] = useState<Action>(); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const auth = () => ({ Authorization: `Bearer ${localStorage.getItem('token') || ''}` });
  const load = () => fetch(`/api/matriz/ejes/${eje}/acciones`, { headers: auth() }).then((response) => response.json()).then((body) => { if (!body.success) throw new Error(body.error); setAcciones(body.data.acciones); setError(''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'No se pudieron cargar las acciones'));
  useEffect(() => { void load(); }, [eje]);
  return <section><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">Matriz de planificación</h2><p className="text-sm text-slate-500">Configure las variables y cantidades de T1 a T4 para cada eje.</p></div><div className="flex gap-2"><label className="text-sm font-semibold">Eje<select value={eje} onChange={(event) => setEje(event.target.value)} className="ml-2 rounded-lg border px-3 py-2">{Array.from({ length: 9 }, (_, index) => String(index + 1)).map((item) => <option key={item} value={item}>Eje {item}</option>)}</select></label><button onClick={() => { setEditing(undefined); setOpen(true); }} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Nueva acción</button></div></div>{error && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><table className="min-w-[1000px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="px-4 py-3">Código</th><th>Acción</th><th>Unidad</th><th>T1</th><th>T2</th><th>T3</th><th>T4</th><th>Meta 2026</th><th>Estado</th><th>Ficha</th></tr></thead><tbody>{acciones.map((accion) => <tr key={accion.accion_id} className="border-b"><td className="px-4 py-3 font-semibold">{accion.codigo}</td><td className="max-w-sm px-4 py-3">{accion.nombre}</td><td>{accion.unidad_medida || '—'}</td>{[1,2,3,4].map((quarter) => <td key={quarter}>{accion.trimestres.find((item) => item.trimestre === quarter)?.cantidadProgramada ?? '—'}</td>)}<td className="font-semibold">{accion.meta_2026}</td><td><span className="rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-700">{accion.estado_planificacion}</span></td><td><button onClick={() => { setEditing(accion); setOpen(true); }} className="text-emerald-700">Editar</button></td></tr>)}</tbody></table></div>{open && <AccionPlanificacionModal ejeCodigo={eje} instituciones={instituciones} accion={editing} onClose={() => setOpen(false)} onSaved={load} />}</section>;
}
