import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
type User = { id?: number; username: string; nombre_completo: string; email: string; institucion_id: number | null; rol: string; activo?: boolean };
type Institution = { id: number; siglas: string; nombre: string };
export function UsuarioModal({ user, institutions, onClose, onSaved }: { user?: User; institutions: Institution[]; onClose: () => void; onSaved: () => void }) {
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<User & { password?: string }>({ defaultValues: { username: user?.username || '', nombre_completo: user?.nombre_completo || '', email: user?.email || '', institucion_id: user?.institucion_id || null, rol: user?.rol || 'observador', password: '' } });
  useEffect(() => { reset({ username: user?.username || '', nombre_completo: user?.nombre_completo || '', email: user?.email || '', institucion_id: user?.institucion_id || null, rol: user?.rol || 'observador', password: '' }); }, [user, reset]);
  const submit = async (values: User & { password?: string }) => { const token = localStorage.getItem('token'); const isEdit = Boolean(user?.id); const response = await fetch(isEdit ? `/api/admin/usuarios/${user!.id}` : '/api/admin/usuarios', { method: isEdit ? 'PUT' : 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...values, institucion_id: values.institucion_id || null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'No se pudo guardar'); if (!isEdit && values.password) { /* password is created with the user */ } onSaved(); onClose(); };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={handleSubmit(submit)} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{user ? 'Editar usuario' : 'Nuevo usuario'}</h2><p className="text-sm text-slate-500">Cuenta institucional</p></div><button type="button" onClick={onClose} className="text-xl text-slate-400">×</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Usuario<input className="mt-1 w-full rounded-lg border p-2.5" {...register('username', { required: 'Requerido' })} />{errors.username && <small className="text-red-600">{errors.username.message}</small>}</label><label className="text-sm font-semibold">Contraseña{user ? <span className="ml-1 font-normal text-slate-400">(opcional aquí)</span> : null}<input type="password" className="mt-1 w-full rounded-lg border p-2.5" {...register('password', { required: user ? false : 'Requerida', minLength: { value: 8, message: 'Mínimo 8 caracteres' } })} />{errors.password && <small className="text-red-600">{errors.password.message}</small>}</label><label className="text-sm font-semibold">Nombre completo<input className="mt-1 w-full rounded-lg border p-2.5" {...register('nombre_completo')} /></label><label className="text-sm font-semibold">Correo electrónico<input type="email" className="mt-1 w-full rounded-lg border p-2.5" {...register('email')} /></label><label className="text-sm font-semibold">Rol<select className="mt-1 w-full rounded-lg border p-2.5" {...register('rol')}><option value="admin">Administrador</option><option value="coordinador_cpi">Coordinador CPI</option><option value="responsable_institucional">Responsable institucional</option><option value="analista_vdssc">Analista VDSSC</option><option value="observador">Observador</option><option value="publico">Público</option></select></label><label className="text-sm font-semibold">Institución<select className="mt-1 w-full rounded-lg border p-2.5" {...register('institucion_id', { valueAsNumber: true })}><option value={0}>Sin institución</option>{institutions.map((institution) => <option key={institution.id} value={institution.id}>{institution.siglas}</option>)}</select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancelar</button><button disabled={isSubmitting} className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Guardar</button></div></form></div>;
}
